### ISSUE TITLE
Folder Name Issue

### ISSUE THREAD

**Issue by DThiwanka** [ravin00/Student_MS#1]
**Don`t add Two Words For Folder Names**

**Comment by DThiwanka** [comment]
> **Don`t add Two Words For Folder Names**

Also there have two Routes folder It's ok, but It's best there are only one routes folder with all route endpoints.

**Comment by ravin00** [comment]
> > **Don`t add Two Words For Folder Names**
> 
> Also there have two Routes folder It's ok, but It's best there are only one routes folder with all route endpoints.

okay ayya
